package sv.edu.udb.javacc;

/* Generated By:JavaCC: Do not edit this line. SQLparserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SQLparserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CREATE = 6;
  /** RegularExpression Id. */
  int DROP = 7;
  /** RegularExpression Id. */
  int DATABASE = 8;
  /** RegularExpression Id. */
  int TABLE = 9;
  /** RegularExpression Id. */
  int USE = 10;
  /** RegularExpression Id. */
  int GO = 11;
  /** RegularExpression Id. */
  int KEY = 12;
  /** RegularExpression Id. */
  int NONULO = 13;
  /** RegularExpression Id. */
  int IPAREN = 14;
  /** RegularExpression Id. */
  int DPAREN = 15;
  /** RegularExpression Id. */
  int COMILLA = 16;
  /** RegularExpression Id. */
  int PUNTO = 17;
  /** RegularExpression Id. */
  int COMA = 18;
  /** RegularExpression Id. */
  int COMILLADOBLE = 19;
  /** RegularExpression Id. */
  int ASIG = 20;
  /** RegularExpression Id. */
  int EQ = 21;
  /** RegularExpression Id. */
  int EQG = 22;
  /** RegularExpression Id. */
  int EQL = 23;
  /** RegularExpression Id. */
  int GREATER = 24;
  /** RegularExpression Id. */
  int LESS = 25;
  /** RegularExpression Id. */
  int NOTEQ = 26;
  /** RegularExpression Id. */
  int AND = 27;
  /** RegularExpression Id. */
  int OR = 28;
  /** RegularExpression Id. */
  int NOT = 29;
  /** RegularExpression Id. */
  int SELECT = 30;
  /** RegularExpression Id. */
  int ALL = 31;
  /** RegularExpression Id. */
  int FROM = 32;
  /** RegularExpression Id. */
  int INSERTINTO = 33;
  /** RegularExpression Id. */
  int VALUES = 34;
  /** RegularExpression Id. */
  int UPDATE = 35;
  /** RegularExpression Id. */
  int SET = 36;
  /** RegularExpression Id. */
  int DELETE = 37;
  /** RegularExpression Id. */
  int WHERE = 38;
  /** RegularExpression Id. */
  int ORDERBY = 39;
  /** RegularExpression Id. */
  int ASC = 40;
  /** RegularExpression Id. */
  int DESC = 41;
  /** RegularExpression Id. */
  int VARCHAR = 42;
  /** RegularExpression Id. */
  int INT = 43;
  /** RegularExpression Id. */
  int DATE = 44;
  /** RegularExpression Id. */
  int FLOAT = 45;
  /** RegularExpression Id. */
  int CHAR = 46;
  /** RegularExpression Id. */
  int NUMBER = 47;
  /** RegularExpression Id. */
  int IDENTIFIER = 48;
  /** RegularExpression Id. */
  int DECIMAL = 49;
  /** RegularExpression Id. */
  int CADENA = 50;
  /** RegularExpression Id. */
  int CARACTER = 51;
  /** RegularExpression Id. */
  int DOUBLEPOINT = 52;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"create\"",
    "\"drop\"",
    "\"database\"",
    "\"table\"",
    "\"use\"",
    "\"go\"",
    "\"primary key\"",
    "\"not null\"",
    "\"(\"",
    "\")\"",
    "\"\\\'\"",
    "\".\"",
    "\",\"",
    "\"\\\"\"",
    "\"=\"",
    "\"==\"",
    "\">=\"",
    "\"<=\"",
    "\">\"",
    "\"<\"",
    "\"<>\"",
    "\"and\"",
    "\"or\"",
    "\"!=\"",
    "\"select\"",
    "\"*\"",
    "\"from\"",
    "\"insert into\"",
    "\"values\"",
    "\"update\"",
    "\"set\"",
    "\"delete\"",
    "\"where\"",
    "\"order by\"",
    "\"asc\"",
    "\"desc\"",
    "\"varchar\"",
    "\"int\"",
    "\"date\"",
    "\"float\"",
    "\"char\"",
    "<NUMBER>",
    "<IDENTIFIER>",
    "<DECIMAL>",
    "<CADENA>",
    "<CARACTER>",
    "\":\"",
  };

}
